### PR TITLE
adds CardaNostra extension

### PR DESCRIPTION
**Pull request by ponthief**

### CODE REVIEW

**Comment by dni** [comment]
lo i checked out the extension and it seemed like fake :D 
:dagger:

**Comment by ponthief** [comment]
what exactly is "fake" about it?

**Comment by dni** [comment]
i guess the default branch `code-quality` tricked me, i did not seem to be any new commits on there. https://github.com/ponthief/cardanostra

**Comment by arcbtc** [comment]
Its a great tool that should exist. We can not merge now however as it has its own dependencies (https://github.com/ponthief/cardanostra/blob/95098b8c73686f8e5bb2a941b2bb8dc11634b9e0/pyproject.toml#L11) and is using monstr which is impossible to vet.
Is it possible to use the nostr client extension instead of monstr as a dependency?

**Comment by arcbtc** [comment]
How is switching over to nostrclient?

**Comment by prusnak** [comment]
Let's close this PR for now and open a new one when CardaNostra releases a version that moved to using `nostrclient`.

**Pull request closed without merging**
