### PR TITLE
feat: max_lnbits_version for older releases

### PR DESCRIPTION
**Pull request by dni**
- this can help the extension manager to know if the current installed lnbits is compatible with an release. 
- this will make it also possible to deprecate unmaintained extension which will break on newer releases

each min_lnbits_version change in the future will mean we have to manually change the max_lnbits_version of the incompatible release aswell, which is fine i think (we already have to change min_version).

this will also help for the `0.13.0` release were every current ext will break. i already added those max version to latest releases upfront in this pr.

new releases will have an max_lnbits_version of `0` or we just remove the key from the json

### CODE REVIEW

**Comment by prusnak** [comment]
max_lnbits_version kind of sounds like the ext still works with this version

trying to come up with a better name, but I can't think of any good one, though ...

**Comment by dni** [comment]
whats so wrong about max version, i think its perfectly fine and describe it exactly

**Comment by motorina0** [comment]
> whats so wrong about max version, i think its perfectly fine and describe it exactly

- `min_version_...` is the lowest version of LNbits that the extension works on
- `min_version_...` is the [@dni fill in the blank please]

**Comment by dni** [comment]
> > whats so wrong about max version, i think its perfectly fine and describe it exactly
> 
>     * `min_version_...` is the lowest version of LNbits that the extension works on
> 
>     * `max_version_...` is the first version which will break compatibility

**Comment by motorina0** [comment]
The logical extrapolation is as follows:

* `min_version_...` is the lowest version of LNbits that the extension works on

* `max_version_...` is the last version of LNbits that the extension works on

The confusion is clear.

`deprecated_from_lnbits_version` (or similar) create no confusion.

**Comment by motorina0** [comment]
add to `src/index.jsx`:
```js
        Maximum LNbits version:{" "}
        {ext.max_lnbits_version || "0.0.0"}
        <br />
```

**Comment by motorina0** [comment]
add to `check.py`:

```py
self.max_lnbits_version = ext.get("max_lnbits_version")

#...

max_lnbits_version = config.get("max_lnbits_version")
print(f"- max_lnbits_version : {max_lnbits_version}")
if max_lnbits_version != self.max_lnbits_version:
    return (
        False,
        f"max_lnbits_version mismatch: {max_lnbits_version} != {self.max_lnbits_version}",
    )
```

**Review by motorina0 — APPROVED** [review]

**Review by arcbtc — APPROVED** [review]

**Pull request merged**
