### PR TITLE
add a simple check for checking extensions.json

### PR DESCRIPTION
**Pull request by prusnak**
simple sanity check for extensions.json
- checks whether provided archive files exists and whether the hashes match
- checks whether icon is a valid image file (via PIL)

### CODE REVIEW

**Comment by prusnak** [comment]
Running the script on main fails, because it correctly finds two issues with icons of `satspay` and `bleskomat`:

```
Checking SatsPay Server extension (satspay 0.1)
- url  : https://github.com/lnbits/satspay/archive/refs/tags/0.1.zip
- hash : ca9cf4da836ca08395a8e759a7848b5caa7d8edbeae7ae0308b27c0f286fae5d (expected)
- hash : ca9cf4da836ca08395a8e759a7848b5caa7d8edbeae7ae0308b27c0f286fae5d (real)
- icon : BROKEN (https://github.com/lnbits/satspay/raw/main/static/images/satspay.png)
FAILED

Checking Bleskomat extension (bleskomat 0.1)
- url  : https://github.com/lnbits/bleskomat/archive/refs/tags/0.1.zip
- hash : abf11879aa7c53afb3adf32405aad08b6aa35c7cc2a22e38c03e8acc48b7a8ff (expected)
- hash : abf11879aa7c53afb3adf32405aad08b6aa35c7cc2a22e38c03e8acc48b7a8ff (real)
- icon : BROKEN (https://github.com/lnbits/bleskomat/raw/main/static/images/bleskomat.png)
FAILED

Failed extensions: satspay bleskomat
```

**Comment by dni** [comment]
very cool LGTM, i fixed the images aswell

**Comment by dni** [comment]
can we add a github workflow aswell?

**Comment by prusnak** [comment]
> correctly finds two issues with icons of `satspay` and `bleskomat`:

Images fixed in https://github.com/lnbits/lnbits-extensions/pull/45

Rebased on current main, the check now goes `Failed extensions: NONE, ALL GOOD!`

**Review by dni — COMMENTED** [review]
LGTM, maybe we can add a github workflow aswell?

**Review by dni — APPROVED** [review]

**Comment by prusnak** [comment]
> LGTM, maybe we can add a github workflow aswell?

Added in 38a30e3

**Comment by dni** [comment]
amazing, do you think we can even push it further like, install the extension and run our lint/typecheck/formatting suite? for a release?

**Comment by prusnak** [comment]
> install the extension and run our lint/typecheck/formatting suite? for a release?

Yes, that's the next step - to unpack the extension and do some stuff with the sources.

But I leave that for some future PR.

**Pull request merged**
