### PR TITLE
chore: remove cashu

### PR DESCRIPTION
**Pull request by dni**
as of request from @callebtc

### CODE REVIEW

**Comment by motorina0** [comment]
Will new tags on the `lnbits/cashu` wallet still create a PR on this repo?

**Comment by arcbtc** [comment]
Thats an odd request.
Where does @callebtc ask for this?
What is the logic here?

**Comment by dni** [comment]
i think they are currently broken

**Review by motorina0 — APPROVED** [review]

**Comment by callebtc** [comment]
This version is very buggy and I'm not going to maintain it anymore. It's not safe to offer this extension without a maintainer. As the author of the extension, I ask you to please remove it. Thank you.

**Review by callebtc — APPROVED** [review]

**Comment by arcbtc** [comment]
So is there a version that is safe, can that not be pr'd in to avoid downtime for users?

**Comment by arcbtc** [comment]
is this up to date?
https://github.com/cashubtc/lnbits-cashu

**Comment by arcbtc** [comment]
Seems so. Lets add that if removing the other.

**Comment by callebtc** [comment]
> Real shame for all the other contributors that you decided to lose the history here btw @callebtc 
> https://github.com/cashubtc/lnbits-cashu/

I don't know how to do that. Feel free to PR.

**Comment by arcbtc** [comment]
Transfer the repo https://github.com/lnbits/cashu/settings
This is something you need to do.

**Comment by arcbtc** [comment]
Is the version on cashubtc up to date?

**Review by arcbtc — APPROVED** [review]

**Pull request merged**
